!!org.peercentrum.core.TopLevelConfig
listenPort: 0    #Set to 0 to select any open port at startup
enableNAT: true
useEncryption: true #For debugging purposes only
applications: 
  - !!org.peercentrum.core.NodeGossipConfig
    bootstrapEndpoint: node1:66.172.33.39:35460
  
  - !!org.peercentrum.h2pk.HashToPublicKeyConfig
    validatorIdentifiers:
      - 123456789
      - qwertyuiop

  - !!org.peercentrum.blob.P2PBlobConfig
    #maximumStorageAllowed: 100M
    transferPricingPerGigabyte: 16129 #About 0.10 USD per GB (amazon charges 0.12)
#      wePayIncoming: 16129 #Max we pay to download data
#      wePayOutgoing: 16129
#      theyPayIncoming: 16129
#      theyPayOutgoing: 16129
#    storagePricingPerGigabytePerDay: 1613
